# Thanks arch linux contributors https://wiki.archlinux.org/title/Alacritty

# font {{{
[font]
size = 12.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = "Regular"
# }}}

# make terminal transparent 
[window]
opacity = 0.85000

# keybinding for spawning a new instance of the terminal in the same directory
[keyboard]
bindings = [
   { key = "Return", mods = "Alt", action = "SpawnNewInstance" }
]
