#!/usr/bin/env bash
# vim: ft=sh

# make sure audio output is muted
ponymix mute

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Load background image if not existed
[[ -f ~/.fehbg ]] && source ~/.fehbg 
