#!/usr/bin/env bash
# vim: ft=sh

# make sure audio output is muted
ponymix mute

# sreen saving parameters 
xset s 900 30
xset dpms 600 600 600     

# Load background image if not existed
[[ -f ~/.fehbg ]] && source ~/.fehbg 
