" ursino's .vimrc

set nocompatible

colorscheme reclipse
syntax on
filetype indent on

" {{{ Plugins 
if !empty(globpath(&runtimepath, 'autoload/plug.vim'))
	call plug#begin('~/.vim/plugged')
	Plug 'vim-python/python-syntax',	{ 'for' : 'python' }
	Plug 'mboughaba/i3config.vim',		{ 'for' : 'i3config' }
	Plug 'dag/vim-fish',			{ 'for' : 'fish' }
	Plug 'ciaranm/detectindent'				

	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'
	Plug 'dense-analysis/ale'

	if has('nvim')
		Plug 'neoclide/coc.nvim', {'branch': 'release'}
	endif
endif

" }}}

" A million settings for addons {{{

let g:python_highlight_all = 1

let g:detectindent_preferred_expandtab = 1
let g:detectindent_preferred_indent = 4
let g:detectindent_preferred_when_mixed = 1
let g:airline_theme='wombat'

"ALE + CoC
let g:ale_fixers = { '*': ['remove_trailing_lines', 'trim_whitespace'], } "by default
let g:ale_fix_on_save = 1

if !empty(globpath(&runtimepath, 'autoload/plug.vim'))
	call plug#end()
endif
" }}}

" Settings {{{

" smarter linebreaks
set linebreak 
set breakindent

set number
set relativenumber
" set spell
set incsearch " search tweaks
set hlsearch
set hidden "allow hiding a buffer
set ignorecase
set smartcase
set mouse+=a "mouse enabled

" }}}
" Disable the default Vim startup message.
set shortmess+=I


" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behavior by default. For example,
" by default, you can't backspace before the insertion point set with 'i'.
" This configuration makes backspace behave more reasonably, in that you can
" backspace over anything.
set backspace=indent,eol,start

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" remove esckeys because of lag and weird behaviour
if !has('nvim')
	set noesckeys
endif
" vim: ft=vim fdm=marker
